### ISSUE TITLE
deleted during filepath walk

### ISSUE THREAD

**Issue by chvsunny** [wal-g/wal-g#579]
Hi,

We are noticing backup failures intermittently with following error.

WARNING: 2020/02/29 23:03:36.923680 /data/postgres/10/5301/base/16419/1030804864.10  deleted during filepath walk
WARNING: 2020/02/29 23:03:36.923688 /data/postgres/10/5301/base/16419/1030804864.11  deleted during filepath walk
WARNING: 2020/02/29 23:03:36.923695 /data/postgres/10/5301/base/16419/1030804864.12  deleted during filepath walk
WARNING: 2020/02/29 23:03:36.923702 /data/postgres/10/5301/base/16419/1030804864.13  deleted during filepath walk
WARNING: 2020/02/29 23:03:36.923709 /data/postgres/10/5301/base/16419/1030804864.2  deleted during filepath walk
WARNING: 2020/02/29 23:03:36.923715 /data/postgres/10/5301/base/16419/1030804864.3  deleted during filepath walk
WARNING: 2020/02/29 23:03:36.923721 /data/postgres/10/5301/base/16419/1030804864.4  deleted during filepath walk
WARNING: 2020/02/29 23:03:36.923727 /data/postgres/10/5301/base/16419/1030804864.5  deleted during filepath walk
WARNING: 2020/02/29 23:03:36.923734 /data/postgres/10/5301/base/16419/1030804864.6  deleted during filepath walk
WARNING: 2020/02/29 23:03:36.923740 /data/postgres/10/5301/base/16419/1030804864.7  deleted during filepath walk
WARNING: 2020/02/29 23:03:36.923746 /data/postgres/10/5301/base/16419/1030804864.8  deleted during filepath walk
WARNING: 2020/02/29 23:03:36.923764 /data/postgres/10/5301/base/16419/1030804864.9  deleted during filepath walk
WARNING: 2020/02/29 23:03:36.923770 /data/postgres/10/5301/base/16419/1030804864_fsm  deleted during filepath walk
WARNING: 2020/02/29 23:03:36.923776 /data/postgres/10/5301/base/16419/1030804864_vm  deleted during filepath walk
panic: packFileIntoTar: failed to open file '/data/postgres/10/5301/base/16419/1030804864.1'
: open /data/postgres/10/5301/base/16419/1030804864.1: no such file or directory

goroutine 2628 [running]:
github.com/wal-g/wal-g/internal.(*Bundle).handleTar.func1(0xc000146460, 0xc002665bf0, 0x2e, 0x19f7660, 0xc002afe680, 0xc002fd6620, 0x0, 0x19f7240, 0xc0003a8000)
        /root/go_projects/src/github.com/wal-g/wal-g/internal/bundle.go:375 +0x10a
created by github.com/wal-g/wal-g/internal.(*Bundle).handleTar
        /root/go_projects/src/github.com/wal-g/wal-g/internal/bundle.go:370 +0x661

$ ./wal-g --version
wal-g version 	271f64f	2019.10.09_19:11:17	PostgreSQL

$ psql -V
psql (PostgreSQL) 10.5

Thanks,
Sunny

**Comment by x4m** [comment]
Hi! thanks for the report!
I belive this must be fixed in https://github.com/wal-g/wal-g/pull/500
not sure we had releases after fix though.

**Comment by chvsunny** [comment]
Thanks. When can we expect a release with this fix?

Thanks,
Sandeep Challa.

**Comment by svesh** [comment]
I tested this on 0.2.15. This bug remained in the new release

**Comment by x4m** [comment]
@svesh can you plz attach relevant logs? I think that you should have different backtrace of goroutines.

**Comment by svesh** [comment]
Logs:
```
panic: packFileIntoTar: failed to open file '/var/postgres/master_db/base/16401/1973388674.73'
: open /var/postgres/master_db/base/16401/1973388674.73: no such file or directory

goroutine 104881 [running]:
github.com/wal-g/wal-g/internal.(*Bundle).handleTar.func1(0xc000172000, 0xc0013482d0, 0x30, 0x1c08ee0, 0xc00547c0d0, 0xc00251ec40, 0x0, 0x1c08b80, 0xc004a88cc0)
        /home/travis/gopath/src/github.com/wal-g/wal-g/internal/bundle.go:383 +0x10a
created by github.com/wal-g/wal-g/internal.(*Bundle).handleTar
        /home/travis/gopath/src/github.com/wal-g/wal-g/internal/bundle.go:378 +0x69b
```
I tested on:
```
wal-g version v0.2.15	f6abd0c	2020.03.24_11:58:03	PostgreSQL
```

**Comment by vladloskut** [comment]
Got the same message:

`WARNING: 2021/10/30 17:13:09.026162 /mnt/data1/11/main/base/16432/321458726_fsm  deleted during filepath walk`

Versions:

PostgreSQL 13.3 (Debian 13.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit

wal-g version 0e286c8 2021.10.15_14:51:52 PostgreSQL

**Comment by usernamedt** [comment]
> Got the same message:
> 
> `WARNING: 2021/10/30 17:13:09.026162 /mnt/data1/11/main/base/16432/321458726_fsm deleted during filepath walk`
> 
> Versions:
> 
> PostgreSQL 13.3 (Debian 13.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
> 
> wal-g version [0e286c8](https://github.com/wal-g/wal-g/commit/0e286c83a15fb48996b19a30e648e8a6bf5e9d17) 2021.10.15_14:51:52 PostgreSQL

Hi! This message itself is not a problem, it just means that the file was removed during the creation of the backup.

**Comment by debebantur** [comment]
Thank you for reporting this issue! It seems to be solved, so i will close it. If you want to add something, feel free to reopen this issue.
