### ISSUE TITLE
Out of memory error on deployment with millions of files in PGDATA

### ISSUE THREAD

**Issue by MannerMan** [wal-g/wal-g#738]
**WAL-G version:** 0.2.15 release binary

**PostgreSQL version:** 9.5

**Operating system/version:** CentOS 7.8

Hi,

I'm evaluating WAL-G as a replacement for my companys current backup system WAL-E. We have a schema-level style of sharding our tenants, where each of our database servers hosts 4000 customer schemas, spread over 16 databases. This has worked great for scalability, but presents a challenge for many backup systems - since this layout results in a lot of
files in postgresql data directory.

Output of `ls -1RL /var/lib/pgsql/9.5/data/ | wc -l`;
`6602805`

So above 6 million files, total size 77gb. Around 5 years ago we deployed WAL-E since it was one of the few backup systems that could handle so many files without a problem. However, since WAL-E is no longer maintained we're looking for alternatives. When testing WAL-G, I'm running out of memory when performing a full-backup. It seems to be some kind of go internal memory error, since the memory of the server is not fully utilized. See graphs;

![Screenshot from 2020-08-24 12-28-14](https://user-images.githubusercontent.com/1773068/91034587-86dbd400-e605-11ea-82d1-6f126609ccc8.png)

Server specs:
* 12gb of ram
* shared_buffers set to 3gb
* 1800 hugepages (~ 3.6 gb to fit shared_buffers )
* vm.overcommit = 2 (not allowed to overcommit)
* 7.8 gb regular memory limit
* CentOS 7
* postgres 9.5
* wal-g 0.2.15

Chunk of the error log;
```
INFO: 2020/08/24 11:49:19.354150 Calling pg_stop_backup()
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x193bfd8, 0x16)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/panic.go:774 +0x72
runtime.sysMap(0xc110000000, 0x10000000, 0x271a7f8)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x27017c0, 0xfbe0000, 0x150b986, 0x288007575f7)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/malloc.go:701 +0x1cd
runtime.(*mheap).grow(0x27017c0, 0x7df0, 0xffffffff)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/mheap.go:1255 +0xa3
runtime.(*mheap).allocSpanLocked(0x27017c0, 0x7df0, 0x271a808, 0x0)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/mheap.go:1170 +0x266
runtime.(*mheap).alloc_m(0x27017c0, 0x7df0, 0x7f20f7020100, 0x0)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/mheap.go:1022 +0xc2
runtime.(*mheap).alloc.func1()
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/mheap.go:1093 +0x4c
runtime.(*mheap).alloc(0x27017c0, 0x7df0, 0x7f2109010100, 0x7f20f7027ff8)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/mheap.go:1092 +0x8a
runtime.largeAlloc(0xfbdfd80, 0x9e0001, 0x7f20f7027ff8)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/malloc.go:1138 +0x97
runtime.mallocgc.func1()
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/malloc.go:1033 +0x46
runtime.systemstack(0x0)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/proc.go:1146
```

Attatched the full log output when performing the backup, including the error as well;
[walg_log.txt](https://github.com/wal-g/wal-g/files/5117236/walg_log.txt)

Target datastore is a local minio S3 instance. Tried `WALG_UPLOAD_DISK_CONCURRENCY` set to `1` and `4`, same result. I see no kernel level OOM-killer logs in syslog, it appears to fail internally.

**Comment by x4m** [comment]
Hi! Can you please rerun upload with WALG_LOG_LEVEL=DEBUG?
I think like we've tried to format JSON for the sentinel here https://github.com/wal-g/wal-g/blob/7c2aa3527695c88ba9efe850cc67464ec76c2e50/internal/backup_push_handler.go#L282

probably there are better ways to format large JSON
But I'm not entirely sure that it's actual problem at hand. It would be perfect if you could recompile wal-g with log lines before and after this statement. If we would be entirely sure it's JSON serialization problem - we could find workaround.
Actually you even can upload empty entinel - basebackup will work anyway.

**Comment by x4m** [comment]
if this marshaling is the only thing that prevents you from backup - we should use stream Encoder https://golang.org/pkg/encoding/json/#Encoder
It must be as simple as few loc

**Comment by MannerMan** [comment]
@x4m Sounds promising! 

Would you like me to re-run with `WALG_LOG_LEVEL=DEBUG` on release 0.2.15, or compile your latest commit b02f986a5723881f2d4b1e1d812cc9a18ce575e4 and run that? Unfortunately I'm not to familiar with Go but I'll manage :)

**Comment by x4m** [comment]
It would be best to run #740 if here will be green test results https://travis-ci.org/github/wal-g/wal-g/builds/720630361
Otherwise any codebase would do, this place did not change for years.

I'm going to the bar currently. Not sure if i'll take my laptop with me.

**Comment by x4m** [comment]
#740 seems to be broken yet...

**Comment by MannerMan** [comment]
@x4m I think I managed to build your branch
```
-bash-4.2$ wal-g --version
wal-g version   4ebb408 2020.08.25_06:16:15     PostgreSQL
```
Running backup now

**Comment by MannerMan** [comment]
@x4m It failed once more unfortunately, actually it seemed to fail quicker and use more memory now;

![Screenshot from 2020-08-25 09-28-56](https://user-images.githubusercontent.com/1773068/91145831-56a03e00-e6b6-11ea-9573-c002fdecaab9.png)


Log attached. Re-running with `DEVEL` log-level now if that can give additional clues.
[walg_fail1.txt](https://github.com/wal-g/wal-g/files/5122053/walg_fail1.txt)

**Comment by x4m** [comment]
Can you plz try backup-push with WALG_UPLOAD_CONCURRENCY set to 1?
I have no idea why memory curve is much more steep now, but we changes AWS SDK in recent commits.

**Comment by x4m** [comment]
Also plz use WALG_COMPRESSION_METHOD=brotli
I see some lz4 stacks, maybe there's a leak

**Comment by x4m** [comment]
I've checked logs, it seems that backup upload was 2x faster than in previous time.
That's why allocations grew our of control...

**Comment by MannerMan** [comment]
@x4m Will do, running backup now with `WALG_UPLOAD_CONCURRENCY` set to `1`, and `WALG_COMPRESSION_METHOD` set to `brotli`. Including the `DEVEL` log level stack trace here as well from the previous re-run if it helps.

[walg_fail2.txt](https://github.com/wal-g/wal-g/files/5122278/walg_fail2.txt)

**Comment by MannerMan** [comment]
It got to the end this time (calling `pg_stop_backup()`) but still spiked in memory and failed

Memory graph;

![Screenshot from 2020-08-25 12-31-54](https://user-images.githubusercontent.com/1773068/91164333-2b761880-e6cf-11ea-81f3-4a4398a82fe1.png)

Stack trace;
[walg_fail3.txt](https://github.com/wal-g/wal-g/files/5123168/walg_fail3.txt)

**Comment by x4m** [comment]
Meh.... Encoder buffers all...
https://github.com/golang/go/issues/7872
as far as I understand it will be fixed here https://go-review.googlesource.com/c/go/+/135595/

I'm looking for other workarounds...

**Comment by x4m** [comment]
We could switch to https://github.com/francoispqt/gojay probably...

**Comment by x4m** [comment]
plz test if green https://travis-ci.org/github/wal-g/wal-g/builds/720967236
otherwise ping me
thanks!

**Comment by MannerMan** [comment]
@x4m Awesome! Thats some quick work - running backup now with compiled with your latest changes
```
-bash-4.2$ ./wal-g --version
wal-g version   b115e98 2020.08.25_12:02:59     PostgreSQL
```

**Comment by x4m** [comment]
@MannerMan sorry, 740 is broken again
I'm a bit new to this json lib and made a mistake (and I do not know exactly what's wrong)
but we really need this lib to avoid formatting backup manifest in memory

**Comment by MannerMan** [comment]
@x4m Alright, no problem - I stopped the running backup meanwhile

**Comment by x4m** [comment]
so far I've considered easyjson and that strange library, all they are not enough robust to feet for sentinel of every supported  in wal-g db....
thinking further

**Comment by x4m** [comment]
@MannerMan can you plz try https://github.com/wal-g/wal-g/pull/741 ?

**Comment by MannerMan** [comment]
@x4m Testing now, running backup

```
-bash-4.2$ ./wal-g --version
wal-g version   11bba03 2020.08.26_05:59:12     PostgreSQL
```

**Comment by MannerMan** [comment]
@x4m Did not help unfortunately.

![Screenshot from 2020-08-26 10-17-49](https://user-images.githubusercontent.com/1773068/91279170-794d5800-e785-11ea-97a7-35e0566a1309.png)

[walg_fail4.txt](https://github.com/wal-g/wal-g/files/5128475/walg_fail4.txt)

**Comment by x4m** [comment]
I'm spamming json lib maintainers a bit. Actually, I've successfully tried all 3 libs, but maybe I'm missing something...

**Comment by x4m** [comment]
Dunno maybe it would be useful to bog golang json maintainers too so they could merge finally changes list about streaming?..

**Comment by jonaz** [comment]
Can we manually loop over the data? I've written some data export tools that can sucessfully export at least 5gb data without using extra memory. It uses this approach: 
```
		tempFile, err := createTempFile()
		if err != nil {
			logrus.Error(err)
			return
		}

		e := json.NewEncoder(tempFile)
		io.WriteString(tempFile, "[")
		i := 0
		for result := range c {
			result := result
			for _, v := range result.Data {
				dataToStream := v
				if i != 0 {
					io.WriteString(tempFile, ",")
				}
				e.Encode(dataToStream)
				i++
			}
		}
		io.WriteString(tempFile, "]")

		tempFile.Close()
```

**Comment by x4m** [comment]
@jonaz we can but this routine is reused by many other DBs with different sentinel types.
We could just take reflective json encoder out of golang and add flush points where it writes data to network not buffering it...

**Comment by x4m** [comment]
we will have to create repo wal-g/json :)
Anyone would volunteer for doing this? :)

**Comment by jonaz** [comment]
Does https://github.com/json-iterator/go work? Saw some memory relates buffer issues in among their fixed issues.

**Comment by x4m** [comment]
@jonaz wow, cool, thanks! Looks promising.

@MannerMan I've pushed new commit to #740 , plz test if CI will be green

**Comment by MannerMan** [comment]
@x4m Great! Running a backup with a new binary compiled from your `oom` branch now. Fingers crossed
```
./wal-g --version
wal-g version   67df11c 2020.08.28_10:22:59     PostgreSQL
```

**Comment by MannerMan** [comment]
Nope, still crashed with 'out of memory' :confused:
[walg_fail5.txt](https://github.com/wal-g/wal-g/files/5142309/walg_fail5.txt)

**Comment by nh-nmurk** [comment]
Hi guys,
just to let you know, we are also experiencing the same problem/errors like was reported by @MannerMan

System specs:
Operating system/version: CentOS 7.8
RAM 62GB
**WAL-G version**: 0.2.15 release binary
**PostgreSQL version**: 11.7
20GB shared_buffers (also set accordingly hugepages )
**vm.overcommit** = 2

**WALG_FILE_PREFIX** is set to local disk (not SSD)

We do not have so many files in PGDATA folder, in our case is cca 82 000 files, 52 databases, instance size is cca 330GB.
The difference is also that we get this error after archive_command is executed, the system is working normally for some time,
but then out of the sudden

```
fatal error: runtime: out of memory
runtime stack:
runtime.throw(0x193bfd8, 0x16)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/panic.go:774 +0x72 fp=0x7ffc567c1578 sp=0x7ffc567c1548 pc=0x9bca02
runtime.sysMap(0xc000000000, 0x4000000, 0x271a7f8)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/mem_linux.go:169 +0xc5 fp=0x7ffc567c15b8 sp=0x7ffc567c1578 pc=0x9a6c65
runtime.(*mheap).sysAlloc(0x27017c0, 0x2000, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/malloc.go:701 +0x1cd fp=0x7ffc567c1660 sp=0x7ffc567c15b8 pc=0x999d5d
runtime.(*mheap).grow(0x27017c0, 0x1, 0xffffffff)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/mheap.go:1255 +0xa3 fp=0x7ffc567c16b0 sp=0x7ffc567c1660 pc=0x9b4d13
runtime.(*mheap).allocSpanLocked(0x27017c0, 0x1, 0x271a808, 0x1)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/mheap.go:1170 +0x266 fp=0x7ffc567c1730 sp=0x7ffc567c16b0 pc=0x9b4ba6
runtime.(*mheap).alloc_m(0x27017c0, 0x1, 0x9e002a, 0x0)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/mheap.go:1022 +0xc2 fp=0x7ffc567c1780 sp=0x7ffc567c1730 pc=0x9b4442
runtime.(*mheap).alloc.func1()
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/mheap.go:1093 +0x4c fp=0x7ffc567c17b8 sp=0x7ffc567c1780 pc=0x9e5a8c
runtime.(*mheap).alloc(0x27017c0, 0x1, 0x1002a, 0x40000)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/mheap.go:1092 +0x8a fp=0x7ffc567c1808 sp=0x7ffc567c17b8 pc=0x9b472a
runtime.(*mcentral).grow(0x27025f8, 0x0)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/mcentral.go:255 +0x7b fp=0x7ffc567c1848 sp=0x7ffc567c1808 pc=0x9a668b
runtime.(*mcentral).cacheSpan(0x27025f8, 0x7f6a6b447000)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/mcentral.go:106 +0x2fe fp=0x7ffc567c18a8 sp=0x7ffc567c1848 pc=0x9a61ae
runtime.(*mcache).refill(0x7f6a6b447008, 0x2a)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/mcache.go:138 +0x85 fp=0x7ffc567c18c8 sp=0x7ffc567c18a8 pc=0x9a5c55
runtime.(*mcache).nextFree(0x7f6a6b447008, 0x271a82a, 0x7f6a6b447008, 0x8, 0xfffffffffffffff8)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/malloc.go:854 +0x87 fp=0x7ffc567c1900 sp=0x7ffc567c18c8 pc=0x99a587
runtime.mallocgc(0x180, 0x191cfa0, 0x1, 0x271a860)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/malloc.go:1022 +0x793 fp=0x7ffc567c19a0 sp=0x7ffc567c1900 pc=0x99aec3
runtime.newobject(0x191cfa0, 0x4000)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/malloc.go:1151 +0x38 fp=0x7ffc567c19d0 sp=0x7ffc567c19a0 pc=0x99b2b8
runtime.malg(0x1516a00008000, 0x2703e68)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/proc.go:3232 +0x31 fp=0x7ffc567c1a10 sp=0x7ffc567c19d0 pc=0x9c5da1
runtime.mpreinit(...)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/os_linux.go:324
runtime.mcommoninit(0x26fc280)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/proc.go:626 +0xc2 fp=0x7ffc567c1a48 sp=0x7ffc567c1a10 pc=0x9bf7c2
runtime.schedinit()
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/proc.go:543 +0x72 fp=0x7ffc567c1aa0 sp=0x7ffc567c1a48 pc=0x9bf422
runtime.rt0_go(0x7ffc567c1ba8, 0x3, 0x7ffc567c1ba8, 0x0, 0x7f6a6a7a3555, 0x2000000000, 0x7ffc567c1ba8, 0x300000000, 0x9e7d20, 0x0, ...)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/asm_amd64.s:214 +0x125 fp=0x7ffc567c1aa8 sp=0x7ffc567c1aa0 pc=0x9e7e55
        2020-08-30 01:37:52.313 UTC [2204] LOG:  archive command failed with exit code 2
2020-08-30 01:37:52.313 UTC [2204] DETAIL:  The failed archive command was: /usr/pgsql-11/bin/archive_command.sh pg_wal/0000000100010EFC000000A7
2020-08-30 01:37:52.480 UTC [2195] LOG:  could not fork autovacuum worker process: Cannot allocate memory
2020-08-30 01:37:52.480 UTC [2195] LOG:  could not fork autovacuum worker process: Cannot allocate memory
```
 Also, there are no OOM killer logs in syslog.

Br,
Nikola

**Comment by MannerMan** [comment]
@x4m I noticed your activity in https://github.com/json-iterator/go/issues/488 - is there a branch with the patched library applied that I can compile and test with?

**Comment by x4m** [comment]
@nh-nmurk I'm not sure your problem originates from WAL-G... do you have atop logs or something similar to identify process consuming a lot of memory? The stacktrace that you provided do not show JSON problems which @MannerMan have.

@MannerMan to test proposed there patch you need to compile patched WAL-G from #740 with jsoniter proposed in that discussion. Meanwhile author of that patch is not maintainer of jsoniter...

**Comment by x4m** [comment]
I have no idea why this patch is not even submitted as pull request. Patch itself looks OK.

**Comment by nh-nmurk** [comment]
@x4m we cann't find any additional information in PostgreSQL nor syslog which could indicate that system is running out of memory.  It can be seen a list of archived WAL logs and then ...out of memory.

Since we had switched back to use test and cp in archive_command, we do not have any problems with memory.

On other production system, we also use wal-g and do not have such problems.

More from Postgresql logs...
```
INFO: 2020/08/30 01:35:28.070103 FILE PATH: 0000000100010EFC000000A0.lz4
INFO: 2020/08/30 01:35:56.702466 FILE PATH: 0000000100010EFC000000A1.lz4
2020-08-30 01:36:08.092 UTC [10833] LOG:  incomplete startup packet
INFO: 2020/08/30 01:36:27.667880 FILE PATH: 0000000100010EFC000000A2.lz4
2020-08-30 01:36:56.487 UTC [11157] LOG:  incomplete startup packet
INFO: 2020/08/30 01:36:57.670646 FILE PATH: 0000000100010EFC000000A3.lz4
INFO: 2020/08/30 01:37:25.479836 FILE PATH: 0000000100010EFC000000A4.lz4
INFO: 2020/08/30 01:37:35.502408 FILE PATH: 0000000100010EFC000000A5.lz4
INFO: 2020/08/30 01:37:40.082181 FILE PATH: 0000000100010EFC000000A6.lz4
2020-08-30 01:37:44.900 UTC [11568] LOG:  incomplete startup packet
fatal error: runtime: out of memory
runtime stack:
runtime.throw(0x193bfd8, 0x16)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/panic.go:774 +0x72 fp=0x7ffc567c1578 sp=0x7ffc567c1548 pc=0x9bca02
runtime.sysMap(0xc000000000, 0x4000000, 0x271a7f8)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/mem_linux.go:169 +0xc5 fp=0x7ffc567c15b8 sp=0x7ffc567c1578 pc=0x9a6c65
runtime.(*mheap).sysAlloc(0x27017c0, 0x2000, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/malloc.go:701 +0x1cd fp=0x7ffc567c1660 sp=0x7ffc567c15b8 pc=0x999d5d
runtime.(*mheap).grow(0x27017c0, 0x1, 0xffffffff)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/mheap.go:1255 +0xa3 fp=0x7ffc567c16b0 sp=0x7ffc567c1660 pc=0x9b4d13
runtime.(*mheap).allocSpanLocked(0x27017c0, 0x1, 0x271a808, 0x1)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/mheap.go:1170 +0x266 fp=0x7ffc567c1730 sp=0x7ffc567c16b0 pc=0x9b4ba6
runtime.(*mheap).alloc_m(0x27017c0, 0x1, 0x9e002a, 0x0)
...
```
or
```
2020-08-30 17:04:29.471 UTC [12967] LOG:  incomplete startup packet
INFO: 2020/08/30 17:04:29.604918 FILE PATH: 0000000100010F02000000F3.lz4
INFO: 2020/08/30 17:05:04.284755 FILE PATH: 0000000100010F02000000F4.lz4
2020-08-30 17:05:17.922 UTC [13486] LOG:  incomplete startup packet
INFO: 2020/08/30 17:05:27.314168 FILE PATH: 0000000100010F02000000F5.lz4
INFO: 2020/08/30 17:05:59.111989 FILE PATH: 0000000100010F02000000F6.lz4
2020-08-30 17:06:08.360 UTC [13909] LOG:  incomplete startup packet
2020-08-30 17:06:31.434 UTC [27498] LOG:  could not fork autovacuum worker process: Cannot allocate memory
TopMemoryContext: 346896 total in 11 blocks; 39728 free (15 chunks); 307168 used
TopMemoryContext: 448648 total in 15 blocks; 105944 free (330 chunks); 342704 used
  pgstat TabStatusArray lookup hash table: 8192 total in 1 blocks; 1456 free (0 chunks); 6736 used
  TopTransactionContext: 8192 total in 1 blocks; 7744 free (0 chunks); 448 used
    Prepared Queries: 16384 total in 2 blocks; 6664 free (3 chunks); 9720 used
  TableSpace cache: 8192 total in 1 blocks; 2096 free (0 chunks); 6096 used
TopTransactionContext: 8192 total in 1 blocks; 7744 free (1 chunks); 448 used
  Type information cache: 24352 total in 2 blocks; 2624 free (0 chunks); 21728 used
    TopMemoryContext: 615936 total in 19 blocks; 236256 free (663 chunks); 379680 usedOperator lookup cache: 24576 total in 2 blocks; 10760 free (3 chunks); 13816 usedpgstat TabStatusArray lookup hash table: 8192 total in 1 blocks; 1456 free (0 chunks); 6736 used
```

this part of log is, presumably, just consequence of out of memory, not the cause...

```
goroutine 1 [syscall]:
github.com/spf13/cobra.(*Command).Execute(...)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:864
github.com/wal-g/wal-g/cmd/pg.Execute()
        /home/travis/gopath/src/github.com/wal-g/wal-g/cmd/pg/pg.go:29 +0x31
main.main()
        /home/travis/gopath/src/github.com/wal-g/wal-g/main/pg/main.go:8 +0x20

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()os.statNolog(0xc0003eed60, 0x18, 0x18, 0x18, 0x18, 0x0)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/os/stat_unix.go:30 +0x31
os.Stat(0xc0003eed60, 0x18, 0x0, 0x0, 0x18, 0xc0003eed60)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/os/stat.go:13 +0x4d
github.com/spf13/afero.OsFs.Stat(...)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/afero/os.go:87
github.com/spf13/viper.exists(0x1c10b00, 0x2718200, 0xc0003eed60, 0x18, 0x18, 0x1926c8a, 0x3)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/viper/util.go:119 +0x49
github.com/spf13/viper.(*Viper).searchInPath(0xc0000d7b00, 0xc0002cdb50, 0xe, 0x2, 0x3b)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/viper/viper.go:1973 +0x344
github.com/spf13/viper.(*Viper).findConfigFile(0xc0000d7b00, 0xc00012ea50, 0x22, 0x0, 0x0)
        /home/travis/
goroutine 1 [syscall]:
os.statNolog(0xc0003eed60, 0x18, 0x18, 0x18, 0x18, 0x0)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/os/stat_unix.go:30 +0x31
os.Stat(0xc0003eed60, 0x18, 0x0, 0x0, 0x18, 0xc0003eed60)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/os/stat.go:13 +0x4d
github.com/spf13/afero.OsFs.Stat(...)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/afero/os.go:87
github.com/spf13/viper.exists(0x1c10b00, 0x2718200, 0xc0003eed60, 0x18, 0x18, 0x1926c8a, 0x3)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/viper/util.go:119 +0x49
github.com/spf13/viper.(*Viper).searchInPath(0xc0000d7b00, 0xc0002cdb50, 0xe, 0x2, 0x3b)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/viper/viper.go:1973 +0x344
github.com/spf13/viper.(*Viper).findConfigFile(0xc0000d7b00, 0xc00012ea50, 0x22, 0x0, 0x0)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/viper/viper.go:1992 +0x128
github.com/spf13/viper.(*Viper).getConfigFile(0xc0000d7b00, 0xc000477b48, 0x1, 0x1, 0xe9ea0f)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/viper/viper.go:1960 +0x5a
github.com/spf13/viper.(*Viper).ReadInConfig(0xc0000d7b00, 0x194af92, 0x21)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/viper/viper.go:1307 +0x8f
github.com/spf13/viper.ReadInConfig(...)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/viper/viper.go:1304
github.com/wal-g/wal-g/internal.InitConfig()
        /home/travis/gopath/src/github.com/wal-g/wal-g/internal/config.go:249 +0x163
github.com/spf13/cobra.(*Command).preRun(0x267df40)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:856 +0x49
github.com/spf13/cobra.(*Command).execute(0x267df40, 0xc0004d6100, 0x1, 0x1, 0x267df40, 0xc0004d6100)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:792 +0x145
github.com/spf13/cobra.(*Command).ExecuteC(0x267d7c0, 0x9ca6fa, 0x2691b40, 0xc000000180)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:792 +0x145
github.com/spf13/cobra.(*Command).ExecuteC(0x267d7c0, 0x9ca6fa, 0x2691b40, 0xc000000180)
goroutine 1 [syscall]:
os.statNolog(0xc0003eed60, 0x18, 0x18, 0x18, 0x18, 0x0)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/os/stat_unix.go:30 +0x31
os.Stat(0xc0003eed60, 0x18, 0x0, 0x0, 0x18, 0xc0003eed60)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/os/stat.go:13 +0x4d
github.com/spf13/afero.OsFs.Stat(...)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/afero/os.go:87
github.com/spf13/viper.exists(0x1c10b00, 0x2718200, 0xc0003eed60, 0x18, 0x18, 0x1926c8a, 0x3)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/viper/util.go:119 +0x49
github.com/spf13/viper.(*Viper).searchInPath(0xc0000d7b00, 0xc0002cdb50, 0xe, 0x2, 0x3b)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/viper/viper.go:1973 +0x344
github.com/spf13/viper.(*Viper).findConfigFile(0xc0000d7b00, 0xc00012ea50, 0x22, 0x0, 0x0)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/viper/viper.go:1992 +0x128
github.com/spf13/viper.(*Viper).getConfigFile(0xc0000d7b00, 0xc000477b48, 0x1, 0x1, 0xe9ea0f)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/viper/viper.go:1960 +0x5a
github.com/spf13/viper.(*Viper).ReadInConfig(0xc0000d7b00, 0x194af92, 0x21)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/viper/viper.go:1307 +0x8f
github.com/spf13/viper.ReadInConfig(...)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/viper/viper.go:1304
github.com/wal-g/wal-g/internal.InitConfig()
        /home/travis/gopath/src/github.com/wal-g/wal-g/internal/config.go:249 +0x163
github.com/spf13/cobra.(*Command).preRun(0x267df40)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:856 +0x49
github.com/spf13/cobra.(*Command).execute(0x267df40, 0xc0004d6100, 0x1, 0x1, 0x267df40, 0xc0004d6100)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:792 +0x145
github.com/spf13/cobra.(*Command).ExecuteC(0x267d7c0, 0x9ca6fa, 0x2691b40, 0xc000000180)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:864
github.com/wal-g/wal-g/cmd/pg.Execute()
        /home/travis/gopath/src/github.com/wal-g/wal-g/cmd/pg/pg.go:29 +0x31
main.main()
        /home/travis/gopath/src/github.com/wal-g/wal-g/main/pg/main.go:8 +0x20

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /home/travis/.gimme/versions/go1.13.9.linux.amd64/src/os/signal/signal_unix.go:29 +0x41

goroutine 21 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0003b2690)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/go.opencensus.io/stats/view/worker.go:154 +0x100
created by go.opencensus.io/stats/view.init.0
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/go.opencensus.io/stats/view/worker.go:154 +0x100
created by go.opencensus.io/stats/view.init.0
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/go.opencensus.io/stats/view/worker.go:32 +0x57

rax    0x0
rbx    0x7f3c00959868
rcx    0xffffffffffffffff
rdx    0x6
rdi    0x37cb
rsi    0x37d1
rbp    0x1c3ef87
rsp    0x7f3bf77fd978
r8     0xa
r9     0x7f3bf77fe700
r10    0x8
r11    0x202
r12    0x7f3be80008c0
r13    0x0
r14    0x1ba3c7c
r15    0x0
rip    0x7f3c005c7387
rflags 0x202
cs     0x33
fs     0x0
gs     0x0
2020-08-30 17:07:04.105 UTC [27526] LOG:  archive command failed with exit code 2
2020-08-30 17:07:04.105 UTC [27526] DETAIL:  The failed archive command was: /usr/pgsql-11/bin/archive_command.sh pg_wal/0000000100010F02000000F8
2020-08-30 17:07:05.216 UTC [27498] LOG:  could not fork autovacuum worker process: Cannot allocate memory
runtime/cgo: runtime/cgo: pthread_create failed: Resource temporarily unavailablepthread_create failed: Resource temporarily unavailable

SIGABRT: abort
```

Thank you for your time
Nikola

**Comment by MannerMan** [comment]
@x4m I think I was able to apply the json-iterator patch to your `oom` branch and compile. The patch failed to apply to `stream_str.go` file, but since it was a one-liner I applied it manually. Running backup with new build now.

**Comment by MannerMan** [comment]
@x4m Hm, not sure whats going on but the backup still failed. Different error this time though;

```
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1581 +0xb32

goroutine 13206650 [select]:
net/http.(*persistConn).writeLoop(0xc0002c8a20)
        /usr/local/go/src/net/http/transport.go:2210 +0x123
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1581 +0xb32

goroutine 13206649 [IO wait]:
internal/poll.runtime_pollWait(0x7f7b665b0928, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc08fe4e418, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc08fe4e400, 0xc057c2e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
net.(*netFD).Read(0xc08fe4e400, 0xc057c2e000, 0x1000, 0x1000, 0xc0002e9380, 0xc00007fdd0, 0xc00007fbe8)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0980c06e8, 0xc057c2e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:184 +0x68
net/http.(*persistConn).Read(0xc0002c8a20, 0xc057c2e000, 0x1000, 0x1000, 0xc00007fed8, 0xafc030, 0xc00007fed8)
        /usr/local/go/src/net/http/transport.go:1758 +0x75
bufio.(*Reader).fill(0xc03fff3980)
        /usr/local/go/src/bufio/bufio.go:100 +0x103
bufio.(*Reader).Peek(0xc03fff3980, 0x1, 0x2, 0x0, 0x0, 0xc0000b2600, 0x0)
        /usr/local/go/src/bufio/bufio.go:138 +0x4f
net/http.(*persistConn).readLoop(0xc0002c8a20)
        /usr/local/go/src/net/http/transport.go:1911 +0x1d6
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1580 +0xb0d
```
I have run the backup twice and got this error both times. Not sure if it actually makes it as far as previously, or if it now fails at an earlier stage.

**Comment by jonaz** [comment]
@MannerMan can you paste whole output? The error seems to be missing only part of the stack trace?

**Comment by MannerMan** [comment]
@jonaz Indeed, I was running a screen-within-a-screen which gobbled the output a bit. Updated the comment above with the full stack trace. Still an out of memory error as it turns out.

**Comment by x4m** [comment]
JFYI we are working on this problem at #1103

**Comment by usernamedt** [comment]
Fixed in https://github.com/wal-g/wal-g/pull/1101. `WALG_WITHOUT_FILES_METADATA` setting allows to disable the files metadata tracking and create backups with millions of files without the OOM errors. The only limitation is that it does not support delta backups.
