### ISSUE TITLE
[ERROR] Failed to fetch backup: Expect pg_control archive, but not found

### ISSUE THREAD

**Issue by nicexe2e4** [wal-g/wal-g#838]
Hello, I try use wal-g for backup=>restore (`wal-g backup-push` => `wal-g backup-fetch`) via S3-compatible service. Backup passed without any errors, but restore stuck on: `ERROR: 2020/12/16 10:26:33.016402 Failed to fetch backup: Expect pg_control archive, but not found`. But: 
```
ryzand@nice:~$ s3cmd ls s3://postgres-database-backups-wal-g/basebackups_005/base_00000001000106090000003D/tar_partitions/ | grep control
2020-12-15 21:16       506   s3://postgres-database-backups-wal-g/basebackups_005/base_00000001000106090000003D/tar_partitions/pg_control.tar.lz4
```
Log with DEBUG=DEVEL: https://pastebin.com/SyC78CA2

ENV: 
wal-g 0.2.19
OS - linux (try 5.4.0 and 5.9.14)
S3 - own s3-compatible service
DB - postgresql 12

P.S. it's pretty works with 0.1.x version (I try wal-g 0.1.17).

**Comment by usernamedt** [comment]
Can you please attach the WAL-G configuration used for backup-fetch?

**Comment by nicexe2e4** [comment]
I change compression from lz4 to brotli, it's new backup and logs now, but same error.
WAL-G config:
```
DEBUG: 2020/12/19 11:38:34.562507 --- COMPILED ENVIRONMENT VARS ---
DEBUG: 2020/12/19 11:38:34.562560 WALG_COMPRESSION_METHOD=brotli
DEBUG: 2020/12/19 11:38:34.562614 AWS_ENDPOINT=https://s3.mycompany.ru
DEBUG: 2020/12/19 11:38:34.562630 PGPORT=5432
DEBUG: 2020/12/19 11:38:34.562660 AWS_REGION=us-east-1
DEBUG: 2020/12/19 11:38:34.562668 WALG_DOWNLOAD_CONCURRENCY=1
DEBUG: 2020/12/19 11:38:34.562674 tablespaces_json={
    "16401": {
        "loc": "/var/lib/postgres/postgreshdd/data",
        "link": "pg_tblspc/16401"
    },
    "16400": {
        "loc": "/var/lib/postgres/ssd2/data",
        "link": "pg_tblspc/16400"
    },
    "tablespaces": [
        "16401",
        "16400"
    ],
    "base_prefix": "/var/lib/postgres/data"
}
DEBUG: 2020/12/19 11:38:34.562690 WALG_S3_PREFIX=s3://postgres-database-backups-wal-g
DEBUG: 2020/12/19 11:38:34.562771 AWS_S3_FORCE_PATH_STYLE=true
DEBUG: 2020/12/19 11:38:34.562776 AWS_SECRET_ACCESS_KEY=key
DEBUG: 2020/12/19 11:38:34.562783 WALG_LOG_LEVEL=DEVEL
DEBUG: 2020/12/19 11:38:34.562788 AWS_ACCESS_KEY_ID=key
DEBUG: 2020/12/19 11:38:34.562795 PGHOST=localhost
DEBUG: 2020/12/19 11:38:34.562822 WALG_PREVENT_WAL_OVERWRITE=false
DEBUG: 2020/12/19 11:38:34.562824 WALG_USE_RATING_COMPOSER=false
DEBUG: 2020/12/19 11:38:34.562909 WALG_UPLOAD_QUEUE=2
DEBUG: 2020/12/19 11:38:34.562917 OPLOG_PUSH_PRIMARY_CHECK_INTERVAL=30s
DEBUG: 2020/12/19 11:38:34.562941 WALG_STORE_ALL_CORRUPT_BLOCKS=false
DEBUG: 2020/12/19 11:38:34.563009 WALG_PG_WAL_SIZE=16
DEBUG: 2020/12/19 11:38:34.563038 OPLOG_PUSH_WAIT_FOR_BECOME_PRIMARY=false
DEBUG: 2020/12/19 11:38:34.563079 WALG_USE_WAL_DELTA=false
DEBUG: 2020/12/19 11:38:34.563094 WALG_TAR_SIZE_THRESHOLD=1073741823
DEBUG: 2020/12/19 11:38:34.563225 WALG_UPLOAD_DISK_CONCURRENCY=1
DEBUG: 2020/12/19 11:38:34.563252 OPLOG_PUSH_STATS_LOGGING_INTERVAL=30s
DEBUG: 2020/12/19 11:38:34.563263 MONGODB_LAST_WRITE_UPDATE_INTERVAL=3s
DEBUG: 2020/12/19 11:38:34.563278 OPLOG_ARCHIVE_AFTER_SIZE=16777216
DEBUG: 2020/12/19 11:38:34.563290 OPLOG_PUSH_STATS_UPDATE_INTERVAL=30s
DEBUG: 2020/12/19 11:38:34.563319 WALG_USE_REVERSE_UNPACK=false
DEBUG: 2020/12/19 11:38:34.563341 WALG_VERIFY_PAGE_CHECKSUMS=false
DEBUG: 2020/12/19 11:38:34.563431 TOTAL_BG_UPLOADED_LIMIT=32
DEBUG: 2020/12/19 11:38:34.563439 WALG_SKIP_REDUNDANT_TARS=false
DEBUG: 2020/12/19 11:38:34.563484 WALG_UPLOAD_CONCURRENCY=16
DEBUG: 2020/12/19 11:38:34.563486 OPLOG_ARCHIVE_TIMEOUT_INTERVAL=60s
DEBUG: 2020/12/19 11:38:34.563506 WALG_DELTA_MAX_STEPS=0
```
sentinel json in txt:
[base_00000001000106B60000004F_backup_stop_sentinels.txt](https://github.com/wal-g/wal-g/files/5719729/base_00000001000106B60000004F_backup_stop_sentinels.txt)

**Comment by usernamedt** [comment]
Can you please also attach the new logs? Looks like they should differ a little bit from the old ones.

**Comment by nicexe2e4** [comment]
https://pastebin.com/z2HTSGnT
okay, new logs.

**Comment by usernamedt** [comment]
Where do you specify the WAL-G-related settings? Via config file or environment variables?

**Comment by nicexe2e4** [comment]
Via export ENV in a bash script.

**Comment by usernamedt** [comment]
> Via export ENV in a bash script.

Can you please attach this script?

There is a mismatch between the COMPILED ENVIRONMENT VARS debug log section and the behavior I see in the provided traceback...

**Comment by nicexe2e4** [comment]
> Can you please attach this script?

Yep, restore.conf:
```
#!/bin/bash

export base_prefix=/var/lib/postgres
export path_to_restore=$base_prefix/data
export hdd_tablespace=$base_prefix/postgreshdd/data
export ssd2_tablespace=$base_prefix/ssd2/data
export db_user=postgres
export gb_group=postgres
export AWS_REGION=us-east-1
export AWS_ACCESS_KEY_ID=key
export AWS_SECRET_ACCESS_KEY=key
#export AWS_ENCRYPT_KEY=False
export AWS_S3_FORCE_PATH_STYLE=true
#export WALG_USE_REVERSE_UNPACK=true
#export WALG_SKIP_REDUNDANT_TARS=true
export WALG_S3_PREFIX=s3://postgres-database-backups-wal-g
export AWS_ENDPOINT=https://s3.mycompany.ru
export WALG_COMPRESSION_METHOD=brotli
export WALG_DOWNLOAD_CONCURRENCY=1
export WALG_LOG_LEVEL=DEVEL
export PGHOST=localhost
export PGPORT=5432
export tablespaces_json="{
    \"16401\": {
        \"loc\": \"${hdd_tablespace}\",
        \"link\": \"pg_tblspc/16401\"
    },
    \"16400\": {
        \"loc\": \"${ssd2_tablespace}\",
        \"link\": \"pg_tblspc/16400\"
    },
    \"tablespaces\": [
        \"16401\",
        \"16400\"
    ],
    \"base_prefix\": \"${path_to_restore}\"
}"
```
restore.sh:
```
#!/bin/bash
IFS=$'\x10'
config_path=$(dirname "$0")
if [[ -f $config_path/restore.conf ]]; then
    source $config_path/restore.conf
else
    echo "File not found $config_path/restore.conf"
    exit 1

blablabla
cat <(echo $tablespaces_json) > $base_prefix/tablespaces.json
wal-g backup-fetch $path_to_restore LATEST --reverse-unpack --skip-redundant-tars --restore-spec $base_prefix/tablespaces.json
blablabla
```
>WALG_USE_REVERSE_UNPACK is set to false, but the traceback includes reverse-unpack related functions.

Yep, u right. Also skip-redundant-tars ENV was affected. It was my mistake:  I didn't uncomment ENV in the first conf file, but added flag in the script, u can see it above. I fixed it now, but error actual :\

**Comment by nicexe2e4** [comment]
Actual debug log without flags and with uncommented ENVs.
https://pastebin.com/1kdr2Tgu

**Comment by usernamedt** [comment]
Does the error persist without `--reverse-unpack` and `--skip-redundant-tars` flags?

**Comment by nicexe2e4** [comment]
Nope
https://pastebin.com/r5FEHp6k

**Comment by dmitrii-singur** [comment]
Hi.  I'm having the same issue now. And It seems s3 api call has limit = 1000 files per request

**Comment by k0ste** [comment]
```
Hi. I'm having the same issue now. And It seems s3 api call has limit = 1000 files per request. For example my backup has ~1800 files
```
S3 index return always up-to 1000 keys. See [API docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjects.html).

**Comment by usernamedt** [comment]
WAL-G uses ListObjectsV2 API: https://github.com/wal-g/storages/blob/424dd6a4bd7495864242bd19d730b0cb6bcec02f/s3/folder.go#L167

Does your S3 API support the pagination [as described here](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html)?

**Comment by dmitrii-singur** [comment]
> WAL-G uses ListObjectsV2 API: https://github.com/wal-g/storages/blob/424dd6a4bd7495864242bd19d730b0cb6bcec02f/s3/folder.go#L167
> 
> Does your S3 API support the pagination [as described here](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html)?

Yep, S3 API supports the pagination. But I see https://github.com/wal-g/storages/blob/424dd6a4bd7495864242bd19d730b0cb6bcec02f/s3/folder.go#L167 doesn't handle last page and nested function always return 'true'. If we want to generate multiple requests we should handle this flag correctly https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#S3.ListObjectsV2Pages

**Comment by usernamedt** [comment]
> > WAL-G uses ListObjectsV2 API: https://github.com/wal-g/storages/blob/424dd6a4bd7495864242bd19d730b0cb6bcec02f/s3/folder.go#L167
> > Does your S3 API support the pagination [as described here](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html)?
> 
> Yep, S3 API supports the pagination. But I see https://github.com/wal-g/storages/blob/424dd6a4bd7495864242bd19d730b0cb6bcec02f/s3/folder.go#L167 doesn't handle last page and nested function always return 'true'. If we want to generate multiple requests we should handle this flag correctly https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#S3.ListObjectsV2Pages

According to the [aws SDK source code](https://raw.githubusercontent.com/aws/aws-sdk-go/master/service/s3/api.go), it should correctly handle the case when the function passed to `ListObjectsV2Pages()` always returns true, i.e. it should just stop iterating through pages.

**Comment by dmitrii-singur** [comment]
> > > WAL-G uses ListObjectsV2 API: https://github.com/wal-g/storages/blob/424dd6a4bd7495864242bd19d730b0cb6bcec02f/s3/folder.go#L167
> > > Does your S3 API support the pagination [as described here](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html)?
> > 
> > 
> > Yep, S3 API supports the pagination. But I see https://github.com/wal-g/storages/blob/424dd6a4bd7495864242bd19d730b0cb6bcec02f/s3/folder.go#L167 doesn't handle last page and nested function always return 'true'. If we want to generate multiple requests we should handle this flag correctly https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#S3.ListObjectsV2Pages
> 
> According to the [aws SDK source code](https://raw.githubusercontent.com/aws/aws-sdk-go/master/service/s3/api.go), it should correctly handle the case when the function passed to `ListObjectsV2Pages()` always returns true, i.e. it should just stop iterating through pages.

Oh, yes... Thanks. I will try to recheck my S3 api

**Comment by nicexe2e4** [comment]
Thanks @dmitrii-singur. Reason for error in s3.ListObjects API version. Our storage doesnt support V2. If I remove some objects for <1000, it's works.
I'll try to recompile app.
@usernamedt are u planning to support old  version API?

**Comment by k0ste** [comment]
Reproducer checks keys of paginatior, for buckets that actually have keys more than 1000. At v2 result should be 1000, at v0 - total keys in bucket.

```python
#!/usr/bin/python
# -*- coding: utf-8 -*-

import boto3
import botocore

def main():
    global s3
    s3 = boto3.client(service_name='s3', endpoint_url='',
                      aws_access_key_id='',
                      aws_secret_access_key='')

    print("list_objects() result: {0}".format(check_list_objects_method('list_objects')))
    print("list_objects_v2() result: {0}".format(check_list_objects_method('list_objects_v2')))

def check_list_objects_method(method):
    s3_bucket = ""

    s3_paginator = s3.get_paginator(method)
    s3_pages = s3_paginator.paginate(Bucket=s3_bucket)

    s3_objects_total = []
    for page in s3_pages:
        for key in page["Contents"]:
            element = key["Key"]
            s3_objects_total.append(element)


    return len(s3_objects_total)


if __name__ == "__main__":
    main()
```

**Comment by k0ste** [comment]
@usernamedt not all storages currently support v2 method.
In go SDK seems exactly like in python SDK - difference only ath method name (at glance): [ListObjectsPages](https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#S3.ListObjectsPages) / [ListObjectsV2Pages](https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#S3.ListObjectsV2Pages)

It's possible to support both methods? For example by ENV options

**Comment by usernamedt** [comment]
I've implemented support for ListObjectsPagesV1 API [in this PR](https://github.com/wal-g/storages/pull/41)

**Comment by nicexe2e4** [comment]
> I've implemented support for ListObjectsPagesV1 API [in this PR](https://github.com/wal-g/storages/pull/41)

Thx, but it doesnt work. I added ```S3_USE_LIST_OBJECTS_V1=true```, but received error about pg_control, when i checked HTTP logs: 
```
2020-12-23 20:33:59.508098 7f2f7dc38700  1 civetweb: 0x5649c012d898: 100.100.104.229 - - [23/Dec/2020:20:33:58 +0700] "GET /postgres-databas
e-backups-wal-g?delimiter=%2F&list-type=2&prefix=basebackups_005%2Fbase_00000001000106090000003D%2Ftar_partitions%2F HTTP/1.1" 200 367777 - 
aws-sdk-go/1.34.3 (go1.15.6; linux; amd64)
```
We can see **list-type=2**.

But, i recompiled app from previous commit and changed ListObjectsV2 to ListObjects and got my backup!

**Comment by usernamedt** [comment]
This is probably because there is still an old WAL-G storages repo version in go.mod of the main WAL-G repo.

**Comment by nicexe2e4** [comment]
@usernamedt nope, i changed go.mod:
```
ryzand@nice:~/walg$ make deps
git submodule update --init
go mod vendor
go: downloading github.com/wal-g/storages v0.0.0-20201222185838-c476223b6b81
...
```

**Comment by usernamedt** [comment]
> @usernamedt nope, i changed go.mod:
> 
> ```
> ryzand@nice:~/walg$ make deps
> git submodule update --init
> go mod vendor
> go: downloading github.com/wal-g/storages v0.0.0-20201222185838-c476223b6b81
> ...
> ```
> 
> I saw S3_USE_LIST_OBJECTS_V1=true in debug log, also.

try cloning this branch and check if it works for you https://github.com/wal-g/wal-g/tree/bump-walg-storages

**Comment by nicexe2e4** [comment]
> [This PR](https://github.com/wal-g/storages/pull/42) should fix it.

Yep, it's works now! 
Thanks, i think after merge u can close task.
